name: pritzel
favicon: null
layout_spectrum: 0.0507819561753422
typography_spectrum: 0.5868879484478384
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.5242903213948011
  lightness: 0.8709589475765824
  saturation: 0.4884969957638532
  rhythmicContrast: 0.8021699970122427
purpose: []
